name: Сервис - Генератор Sitemap

on:
  push:
    branches:
      - main

jobs:
  build_sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://github.io

      - name: Commit and Push Sitemap
        run: |
          if [[ `git status --porcelain sitemap.xml` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@://github.com'
            git add sitemap.xml
            git commit -m "Автоматическое обновление sitemap.xml"
            git push
          else
            echo "Изменений в структуре сайта нет."
          fi
