name: Сервис - Бэкап на Диск Google

on:
  push:
    branches:
      - main
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  run_backup:
    runs-on: ubuntu-latest
    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v4

      - name: Установка Rclone из репозитория Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Настройка авторизации через Сервисный аккаунт Google
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > ~/.config/google-key.json
          
          cat << EOF > ~/.config/rclone/rclone.conf
          [gdrive]
          type = drive
          scope = drive
          service_account_file = ~/.config/google-key.json
          EOF

      - name: Создание архива сайта во временной папке
        run: tar --exclude='.git' --exclude='.github' -czf /tmp/site-backup.tar.gz .

      - name: Отправка архива на Google Диск
        run: rclone copy /tmp/site-backup.tar.gz gdrive:GitHub_Backups
