name: Сервис - Бэкап на Диск Google

on:
  push:
    branches:
      - main
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  run_backup:
    runs-on: ubuntu-latest
    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v4

      - name: Установка Rclone (Официальный модуль)
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            [gdrive]
            type = drive
            scope = drive
            service_account_file = google-key.json

      - name: Настройка ключа авторизации робота
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > google-key.json

      - name: Создание архива сайта
        run: tar --exclude='.git' --exclude='.github' --exclude='google-key.json' -czf site-backup.tar.gz .

      - name: Отправка архива на Google Диск
        run: rclone copy site-backup.tar.gz gdrive:GitHub_Backups
