name: Сервис - Бэкап на Диск Google

on:
  push:
    branches:
      - main
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  run_backup:
    runs-on: ubuntu-latest
    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v4

      - name: Установка Rclone из репозитория Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Настройка чистой авторизации Google
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > /tmp/google-key.json
          
          cat << 'EOF' > ~/.config/rclone/rclone.conf
          [gdrive]
          type = drive
          scope = drive
          service_account_file = /tmp/google-key.json
          EOF

      - name: Создание уникального архива сайта
        run: |
          # Создаем имя файла с текущей датой и временем
          FILENAME="backup-$(date +'%Y-%m-%d_%H-%M').tar.gz"
          tar --exclude='.git' --exclude='.github' -czf "/tmp/$FILENAME" .
          # Передаем имя файла в следующий шаг
          echo "BACKUP_FILENAME=$FILENAME" >> $GITHUB_ENV

      - name: Отправка архива на Google Диск
        run: rclone copy "/tmp/${{ env.BACKUP_FILENAME }}" gdrive:GitHub_Backups
