name: Поисковик - Яндекс

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'sitemap.xml' # Защита от бесконечного цикла при обновлении карты сайта

jobs:
  yandex_auto_index:
    runs-on: ubuntu-latest
    steps:
      - name: Авто-отправка карты сайта в Яндекс
        uses: jakob-bagterp/index-now-submit-sitemap-action@v1
        with:
          host: fast-pay-store.github.io
          api_key: cnjxrbphtybz
          api_key_location: https://fast-pay-store.github.io/cnjxrbphtybz.txt
          sitemap_locations: https://fast-pay-store.github.io/sitemap.xml
          endpoint: yandex
