name: Поисковик - Bing

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'sitemap.xml'
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  bing_indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Отправка страниц в Bing
        run: |
          curl -X POST "https://bing.com" \
          -H "Content-Type: application/json; charset=utf-8" \
          -d '{
            "host": "fast-pay-store.github.io",
            "key": "cnjxrbphtybz",
            "keyLocation": "https://github.io",
            "urlList": [
              "https://github.io",
              "https://github.ioindex.html",
              "https://github.ioshoptitans-bot/",
              "https://github.iobot-dungeon-crusher/",
              "https://github.iotrofei-rybalka2/"
            ]
          }'
