name: Сервис - Уведомления в Telegram

on:
  workflow_run:
    workflows:
      - "Сервис - Бэкап на Диск Google"
      - "Поисковик - Яндекс"
      - "Поисковик - Google"
      - "Поисковик - Bing"
      - "Сервис - Тестировщик ссылок"
    types:
      - completed

jobs:
  send_telegram_status:
    runs-on: ubuntu-latest
    steps:
      - name: Отправка уведомления ТОЛЬКО при ошибке
        if: github.event.workflow_run.conclusion != 'success'
        run: |
          WORKFLOW_NAME="${{ github.event.workflow_run.name }}"
          CONCLUSION="${{ github.event.workflow_run.conclusion }}"
          RUN_ID="${{ github.event.workflow_run.id }}"
          REPO_URL="https://github.com/${{ github.repository }}"
          LOG_URL="${REPO_URL}/actions/runs/${RUN_ID}"

          STATUS_EMOJI="❌"
          STATUS_TEXT="Завершился с ошибкой!"

          MESSAGE="${STATUS_EMOJI} Робот: ${WORKFLOW_NAME}
          Статус: ${STATUS_TEXT}
          
          Логи сборки: ${LOG_URL}"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"${MESSAGE}\"}"
