name: Сервис - Вставка виджетов и контактов

on:
  push:
    branches:
      - main
    paths:
      - '**/index.html'
  workflow_dispatch:

jobs:
  inject_widgets:
    runs-on: ubuntu-latest
    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v4

      - name: Вшивание канонических ссылок и addons.js
        shell: bash
        run: |
          TARGET_FOLDERS=("shoptitans-bot" "bot-dungeon-crusher" "trofei-rybalka2")
          INJECT_LINE='<script src="./addons.js"></script>'

          for folder in "${TARGET_FOLDERS[@]}"; do
              file="./$folder/index.html"
              
              if [ -f "$file" ]; then
                  # Очищаем старые привязки скрипта
                  sed -i '/addons.js/d' "$file"
                  # Очищаем старые канонические теги, если они были
                  sed -i '/rel="canonical"/d' "$file"
                  
                  # 1. Жестко вшиваемaddons.js перед закрывающим тегом </body>
                  perl -i -pe "s|(<\/body>)|${INJECT_LINE}\1|gi" "$file"
                  
                  # 2. Генерируем правильный канонический URL для этой папки
                  CANONICAL_TAG="<link rel=\"canonical\" href=\"https://github.io{folder}/\" />"
                  
                  # 3. Вставляем канонический тег в самое начало блока <head>
                  perl -i -pe "s|(<head>)|\\1\n    ${CANONICAL_TAG}|gi" "$file"
                  echo "Настройки успешно вшиты в папку: $folder"
              fi
          done

      - name: Сохранение изменений в репозиторий
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@://github.com'
            git add .
            git commit -m "Автоматическое вшивание канонических URL и addons.js"
            git push
          else
            echo "Изменений нет."
          fi
