name: Сервис - Бэкап на Google Диск

on:
  push:
    branches:
      - main
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v4

      - name: Установка Rclone
        run: sudo curl https://rclone.org | sudo bash

      - name: Настройка авторизации Google Диска
        run: |
          mkdir -p ~/.config/rclone
          echo "[gdrive]" > ~/.config/rclone/rclone.conf
          echo "type = drive" >> ~/.config/rclone/rclone.conf
          echo "scope = drive" >> ~/.config/rclone/rclone.conf
          echo "token = ${{ secrets.RCLONE_CONFIG_DATA }}" >> ~/.config/rclone/rclone.conf

      - name: Создание архива сайта
        run: tar --exclude='.git' --exclude='.github' -czf site-backup.tar.gz .

      - name: Отправка архива на Google Диск
        run: rclone copy site-backup.tar.gz gdrive:GitHub_Backups
