name: Сервис - Вставка виджетов и контактов

on:
  push:
    branches:
      - main
    paths:
      - '**/index.html'
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  inject_widgets:
    runs-on: ubuntu-latest
    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v4

      - name: Подключение внешнего скрипта addons.js через Python
        shell: python
        run: |
          import os

          # НАГЛЯДНЫЙ ВЕРТИКАЛЬНЫЙ СПИСОК ПАПОК
          target_folders = [
              "shoptitans-bot",
              "bot-dungeon-crusher",
              "trofei-rybalka2",
          ]
          
          inject_line = '<script src="./addons.js"></script>'
          favicon_line = '    <link rel="icon" type="image/png" href="https://fast-pay-store.github.io/favicon.png" />'

          for folder in target_folders:
              file_path = f"./{folder}/index.html"
              if os.path.exists(file_path):
                  with open(file_path, "r", encoding="utf-8") as f:
                      content = f.read()
                  
                  # Полностью очищаем старые версии вставок, возвращая HTML к чистому виду
                  content = content.replace(inject_line, "")
                  content = content.replace(favicon_line + "\n", "")
                  
                  # Вставляем только строчку подключения внешнего JS скрипта перед </body>
                  if "</body>" in content:
                      content = content.replace("</body>", f"{inject_line}</body>")
                  elif "</BODY>" in content:
                      content = content.replace("</BODY>", f"{inject_line}</BODY>")
                  
                  with open(file_path, "w", encoding="utf-8") as f:
                      f.write(content)
                  print(f"Скрипт addons.js успешно привязан к папке: {folder}")

      - name: Сохранение изменений в репозиторий
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "Привязка скрипта кнопок по чистому списку папок"
            git push
          else
            echo "Изменений в репозитории нет."
          fi
